live_config_reload = true

shell = "nu"

import = [
    "~/.config/alacritty/themes/gruvbox_material.toml"
]

[font]
size = 11.0

[font.normal]
family = "ComicShannsMono Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 10000
