<<<<<<< HEAD
=======
[terminal]
shell = "nu"

[general]
import = [
    "~/.config/alacritty/themes/gruvbox_material.toml"
]
live_config_reload = true
>>>>>>> b7dad4b (alacritty: Update configuration to remove deprecated features)

[window]
opacity = 1.0

[font]
size = 13.0

[font.normal]
family = "ComicShannsMono Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 10000

[general]
live_config_reload = true

import = [
    "~/.config/alacritty/themes/gruvbox_material.toml"
]

[terminal]

shell = "nu"
