#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#enable picom
picom --config ~/.config/picom.config

#set background
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-fill "/home/caleb/Nextcloud/Pictures/Wallpapers/6k_Bridge.jpg"
fi

#set xrandr
xrandr --output HDMI-A-0 --mode 2560x1440 --rate 143.91

#start polybar
polybar

#start nm-applet
nm-applet

#start dunst
dunst -c ~/.config/dunst/dunstrc

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# index=0
# monitors="$(polybar -m | sed s/:.*//)"
# leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
# do
#   let indextemp=index+1
#   monitor=$(sed "$indextemp!d" <<<"$monitors")
#   barname="mainbar$index"
#   monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
#   let index=indextemp
# done

