theme = "gruvbox"

[editor]
auto-completion = true
auto-format = true
auto-info = true
auto-pairs = true
completion-trigger-len = 2
color-modes = true
bufferline = "multiple"
idle-timeout = 100
mouse = false
middle-click-paste = false
line-number = "relative"
scrolloff = 5
rulers = [80]
gutters = ["diagnostics", "spacer", "line-numbers", "diff"]

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.file-picker]
hidden = false

[keys.normal]
C-r = "repeat_last_motion"
